spring.application.name=spring-mvc-demo

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=betinka
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

logging.level.org.hibernate.persister.entity=ERROR
logging.level.org.springframework.security=DEBUG